### ISSUE TITLE
When GeckoDriver Calms Down

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/selenium-assistant#28]
Switch to using: https://github.com/vladikoff/node-geckodriver

At the moment the geckodriver keeps changing it's requirements and it's pretty unpredictable so having control would be good, but once it's calmed down delete code, USE THIS, profit!!!.

**Comment by koko654321** [comment]
Why are u doing what u can to ruin my life? one of the nurses have helped me when i show her this, and shes going to see polise today.I have not even meet u why do u have to hack my netbank? and uve destroyed pcs and nphones for 2500 dollar and destroyed comp and phones for 3000 so when the polise find u its going to be expensive for u-.---

**Comment by gauntface** [comment]
Seems to be working now and gets around the horrible GH_TOKEN requirements.
