### ISSUE TITLE
npm run test fails on macOS with Safari 10

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/selenium-assistant#45]
Safari 10 mostly works with this package (after you've [enabled Remote Automation](https://webkit.org/blog/6900/webdriver-support-in-safari-10/)), taking advantage of the built-in webdriver that ships with macOS. There's a small modification that needs to be made to the tests to work around the fact that the webdriver doesn't expose browser info (at least not in the same way that other browsers do). The following needs to be skipped for Safari 10:

```js
function testBrowserInfo(specificBrowser) {
  const versionString = specificBrowser.getRawVersionString();
  (versionString === null).should.equal(false);

  const versionNumber = specificBrowser.getVersionNumber();
  versionNumber.should.not.equal(-1);
}
```

I'll put together a quick PR to blacklist that check for Safari, but if you have a better idea, @gauntface, I'm open to that as well.

**Comment by addyosmani** [comment]
Before merging in #46 I'd love to hear what Matt thinks on S10

**Comment by gauntface** [comment]
My version of safari 10 didn't install the web driver binary so couldn't test (and the extension no longer works for me).

I'd much rather fix the version number than remove from the test.

Note: these tests shouldn't run on travis or during a release. They are purely run on manual tests.

**Comment by gauntface** [comment]
This and #49 will be top of my list for things to fix in Q4.
