### ISSUE TITLE
Is there a add-on similar to FireFox HARExport in Chrome?

### ISSUE THREAD

**Issue by vuyyala** [GoogleChrome/selenium-assistant#67]
Hi all,
        I am trying to download HAR from chrome using Selenium Webdriver using python script (code). Firefox has a nice add-on Firefox HarExport to automate this process of downloading HAR from browser.  Usage of Firefox HARExport with Selenium driver.
I am using Selenium chrome driver to open chrome browser and then manually open networks tab and finally use "Save as HAR with content" or "Copy all as HAR".Can't this process be automated as it is done for Firefox? How does chrome deals with this issue?
I don't want to use proxies like BMP because they don't work with  QUIC packets.
 Anyone having any idea on how to automate the download of HAR from chrome please comment .I have been searching for this issue for a long time.

**Comment by gauntface** [comment]
Sorry I've not got any expierience of HAR's but it might be worth asking on stackoverflow if you haven't already.

This may be something that the Chrome debug protocol gives you access to (it's the protocol used by DevTools), but it will be specific to Chrome.

**Comment by vuyyala** [comment]
Can you explain a bit more about your last sentence? I am working specifically on chrome only.
